repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        additional_dependencies: ['prettier@3.0.0']
        files: \.(js|jsx|ts|tsx|json|css|md|html)$
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        additional_dependencies: ['eslint@8.56.0']
        files: \.(js|jsx|ts|tsx)$
