repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies: ['prettier@3.3.3', '@trivago/prettier-plugin-sort-imports@4.3.0']
        files: ^frontend/.*\.(js|jsx|ts|tsx|json|css|md|html)$
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.0
    hooks:
      - id: eslint
        args: [--fix, --config, frontend/.eslintrc.cjs]
        additional_dependencies:
          [
            'eslint@9.0.0',
            '@typescript-eslint/eslint-plugin@7.0.0',
            '@typescript-eslint/parser@7.0.0',
            'eslint-plugin-react@7.33.0',
            'eslint-plugin-react-hooks@4.6.0',
            'eslint-plugin-react-refresh@0.4.5',
          ]
        files: ^frontend/.*\.(js|jsx|ts|tsx)$
