# This is the single, centralized pre-commit configuration for the entire repository.

repos:
  # ===== Python Backend Hooks =====
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
        # Run only on files in the backend directory
        files: ^backend/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        args: ["--fix"]
        language_version: python3
        # Run only on files in the backend directory
        files: ^backend/

  # ===== Frontend Hooks =====
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0 # Using a slightly newer version
    hooks:
      - id: prettier
        # Run only on files in the frontend directory
        files: ^frontend/.*\.(js|jsx|ts|tsx|json|css|md|html)$
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.0 # Using a slightly newer version
    hooks:
      - id: eslint
        args: [--fix, --config, frontend/eslint.config.js]
        additional_dependencies:
          [
            "eslint@9.0.0",
            "@typescript-eslint/eslint-plugin@7.0.0",
            "@typescript-eslint/parser@7.0.0",
            "eslint-plugin-react@7.33.0",
            "eslint-plugin-react-hooks@4.6.0",
            "eslint-plugin-react-refresh@0.4.5",
          ]
        # Run only on files in the frontend directory
        files: ^frontend/.*\.(js|jsx|ts|tsx)$
