# .pre-commit-config.yaml
# Root pre-commit configuration for the NEFAC monorepo.

repos:
  # ===================================================================
  # Backend Hooks (Python)
  # ===================================================================
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        # Black will read its configuration from backend/pyproject.toml
        files: ^backend/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: [--fix]
        # Ruff will read its configuration from backend/pyproject.toml
        files: ^backend/

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          [
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--in-place",
            "--exclude=docs,faiss_store,*.pkl,*.pdf,*.txt",
          ]
        files: ^backend/

  # ===================================================================
  # Frontend Hooks (TypeScript/JavaScript)
  # ===================================================================
  - repo: local
    hooks:
      - id: prettier-frontend
        name: Prettier (Frontend)
        language: system
        entry: npm run check-format --prefix frontend
        types: [javascript, jsx, ts, tsx, json, css, markdown, html]
        files: ^frontend/

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        # The --config flag is needed because we are running from the root.
        args: [--fix, --config, frontend/.eslintrc.cjs]
        additional_dependencies:
          - "eslint@8.56.0"
          - "@typescript-eslint/eslint-plugin@7.0.0"
          - "@typescript-eslint/parser@7.0.0"
          - "eslint-plugin-react@7.33.0"
          - "eslint-plugin-react-hooks@4.6.0"
          - "eslint-plugin-react-refresh@0.4.5"
        # Run only on files in the frontend directory
        files: ^frontend/
