"""
LangGraph retrieval subgraph with a dynamic, hybrid strategy.
It can combine graph search and document search based on a plan generated by an LLM.
"""

import logging
from typing import Any, Dict, List

from langchain.retrievers import EnsembleRetriever
from langchain.retrievers.contextual_compression import ContextualCompressionRetriever
from langchain_cohere import CohereRerank
from langchain_core.documents import Document
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI
from langgraph.graph import END, StateGraph
from pydantic import BaseModel

from src.config.constant import RETRIEVAL_SELECTION_MODEL_NAME
from src.core.agents.retrieval.graph_retrieval import graph_tool_node
from src.core.agents.retrieval.keyword_retrieval import keyword_retriever

# We need the vector_store object to dynamically create retrievers with different `k` values
from src.core.agents.retrieval.vector_retrieval import vector_retriever
from src.schemas.core_types import AgentState

logger = logging.getLogger(__name__)

llm = ChatOpenAI(temperature=0, model=RETRIEVAL_SELECTION_MODEL_NAME)
# --- Retrieval Planning Prompt ---
RETRIEVAL_PLANNING_PROMPT = """You are an expert at selecting the optimal retrieval strategy for legal queries for NEFAC’s First Amendment resources. Your goal is to choose the best method(s) to answer the user's query by creating a detailed retrieval plan.

You have the following retrieval methods available, and you can choose one or both:

1.  `graph_search`:
    *   **What it is:** A knowledge graph search (using Neo4j).
    *   **Best for:** Queries about relationships, entities, and structured data. It's excellent for understanding how different entities like people, organizations, and legal cases are connected.

2.  `document_search`:
    *   **What it is:** A hybrid search that combines two techniques:
        *   Keyword search (BM25): For finding exact terms, names, and citations.
        *   Semantic vector search: For finding conceptually related information and answering broader questions.
    *   **Best for:** A wide range of queries, from finding specific documents to exploring general legal concepts.

**Decision Guidelines & Heuristics:**

Carefully analyze the user's query and choose one or more methods based on the following patterns:

*   **Choose `graph_search` (or both) if the query contains:**
    *   **Entity & Relationship Patterns:** Look for phrases like `who is`, `what is the relationship between`, `connected to`, `involved in`, etc.
    *   **Examples:**
        *   "What is the connection between the ACLU and cases involving FOIA?" (Good candidate for BOTH `graph_search` and `document_search`)
        *   "Who is John Doe and what organizations is he affiliated with?" (Good candidate for `graph_search`)
        *   "List all cases decided by the Supreme Court that cite the 'public records law'." (Good candidate for BOTH)

*   **Choose `document_search` if the query contains:**
    *   **Exact-Term Patterns:** Look for specific legal citations (`FOIA`, `Section 230`), laws (`public records law`), or proper names (`Jane Smith`, `ACLU`). While the graph may contain these, document search is better for retrieving the source text.
        *   **Example:** "Find documents discussing Section 230."
    *   **Conceptual Patterns:** Look for broad questions about legal concepts, principles, or approaches.
        *   **Example:** "What are the main legal arguments regarding student speech rights?"
    *   **General Explanatory Questions:** Look for words like `how`, `why`, `explain`, `describe`.
        *   **Example:** "Explain the principle of prior restraint."

**Final Output: The Retrieval Plan**

You must return only a valid JSON object that outlines the retrieval plan. The plan must specify the `methods` to use and the parameters for each stage.

**Plan Parameters:**
- `methods`: A list containing one or both of `"graph_search"` and `"document_search"`.
- `doc_search_params`: (Required if `document_search` is in `methods`)
    - `weights`: An object with `keyword` and `vector` weights that sum to 1.0.
    - `vector_k`: The number of documents to fetch from the vector store (before fusion). Default is 10.
    - `keyword_k`: The number of documents to fetch from the keyword search (before fusion). Default is 10.
    - `ensemble_k`: The number of documents to keep from the combined `document_search` results (after fusion). Default is 10.
- `rerank_k`: The final number of documents to return after all retrieval, combination, and reranking steps. This should be a small, focused number (e.g., 5).

**Example for a complex query needing both graph and document context:**
*Query: "What is the connection between the ACLU and cases involving FOIA?"*
```json
{
  "methods": ["graph_search", "document_search"],
  "doc_search_params": {
    "weights": { "keyword": 0.5, "vector": 0.5 },
    "vector_k": 8,
    "keyword_k": 15,
    "ensemble_k": 10
  },
  "rerank_k": 5
}
```

**Example for a conceptual query needing only document search:**
*Query: "What are the main legal arguments regarding student speech rights?"*
```json
{
  "methods": ["document_search"],
  "doc_search_params": {
    "weights": { "keyword": 0.4, "vector": 0.6 },
    "vector_k": 10,
    "keyword_k": 5,
    "ensemble_k": 10
  },
  "rerank_k": 5
}
```
"""


class DocumentSearchParamsModel(BaseModel):
    weights: Dict[str, float]
    vector_k: int
    keyword_k: int
    ensemble_k: int


class RetrievalPlanModel(BaseModel):
    methods: List[str]
    doc_search_params: DocumentSearchParamsModel
    rerank_k: int


class RetrievalSubgraphState(AgentState):
    """State for the retrieval subgraph."""

    # The `retrieval_query` from AgentState is used as the input query.
    retrieval_query: str = ""
    retrieval_plan: Dict[str, Any] = {}
    graph_documents: List[Document] = []
    document_search_documents: List[Document] = []
    documents: List[Document] = []  # Final combined list


def plan_retrieval_node(state: AgentState) -> dict:
    query = state.retrieval_query
    logger.info(f"Planning retrieval for query: '{query}'")

    prompt = ChatPromptTemplate.from_messages(
        [
            ("system", RETRIEVAL_PLANNING_PROMPT),
            ("human", "Query: {query}"),
        ]
    ).with_structured_output(RetrievalPlanModel)
    chain = prompt | llm

    plan: RetrievalPlanModel = chain.invoke({"query": query})
    logger.info(f"Retrieval plan created: {plan.json()}")
    return {"retrieval_plan": plan.dict()}


def ensemble_retrieval_node(state: RetrievalSubgraphState) -> RetrievalSubgraphState:
    """Retrieves documents using a dynamically configured ensemble retriever."""
    plan = state["retrieval_plan"]
    params = plan.get("doc_search_params", {})
    weights_dict = params.get("weights", {"keyword": 0.5, "vector": 0.5})
    weights = [weights_dict.get("keyword", 0.5), weights_dict.get("vector", 0.5)]
    vector_k = params.get("vector_k", 10)
    keyword_k = params.get("keyword_k", 10)
    ensemble_k = params.get("ensemble_k", 10)
    rerank_k = plan.get("rerank_k", 5)
    query = state["retrieval_query"]

    logger.info(f"Performing ensemble retrieval with params: weights={weights}, vector_k={vector_k}, ensemble_k={ensemble_k}")

    # Create a new vector retriever with the specified `k`

    ensemble_retriever = EnsembleRetriever(retrievers=[keyword_retriever.bind(top_k=keyword_k), vector_retriever.bind(k=vector_k)], weights=weights)
    compressor = CohereRerank(model="rerank-english-v3.0")
    compression_retriever = ContextualCompressionRetriever(base_compressor=compressor, base_retriever=ensemble_retriever)
    reranked_docs = compression_retriever.invoke(query)
    final_docs = reranked_docs[:rerank_k]
    return {"document_search_documents": final_docs}


def graph_retrieval_node(state: RetrievalSubgraphState) -> RetrievalSubgraphState:
    """Retrieves documents using graph search."""
    query = state["retrieval_query"]
    logger.info("Performing graph retrieval.")
    documents = graph_tool_node.invoke(query, state=state)
    logger.info(f"Retrieved {len(documents)} documents from graph search.")
    return {"graph_documents": documents}


def combine_documents_node(state: RetrievalSubgraphState) -> RetrievalSubgraphState:
    """Combines and deduplicates documents from all retrieval sources."""
    logger.info("Combining and deduplicating documents.")
    all_docs = state.get("document_search_documents", []) + state.get("graph_documents", [])
    return {"documents": all_docs}


# --- Graph Definition ---
workflow = StateGraph(RetrievalSubgraphState)

workflow.add_node("planner", plan_retrieval_node)
workflow.add_node("ensemble_retrieval", ensemble_retrieval_node)
workflow.add_node("graph_retrieval", graph_retrieval_node)
workflow.add_node("combine_documents", combine_documents_node)
workflow.set_entry_point("planner")


def route_after_planning(state: RetrievalSubgraphState):
    """Return a list of nodes to run in parallel based on the plan."""
    methods = state.get("retrieval_plan", {}).get("methods", [])

    nodes_to_run = []
    if "document_search" in methods:
        nodes_to_run.append("ensemble_retrieval")
    if "graph_search" in methods:
        nodes_to_run.append("graph_retrieval")

    return nodes_to_run if nodes_to_run else ["combine_documents"]


workflow.add_conditional_edges("planner", route_after_planning)

workflow.add_edge("ensemble_retrieval", "combine_documents")
workflow.add_edge("graph_retrieval", "combine_documents")
workflow.add_edge("combine_documents", END)
# Compile the graph into a runnable object
retrieval_subgraph = workflow.compile()
