"""
Allsrc.config prompt definitions for the NEFAC chatbot.
All prompts are original, detailed, and comprehensive as requested.
"""

# Import all prompts from individual modules
from src.config.prompt.base import (
    BASE_PROMPT,
)
from src.config.prompt.graph import DEFAULT_CYPHER_GENERATION_TEMPLATE, DEFAULT_GRAPH_QA_PROMPT
from src.config.prompt.query_transformation import (
    DEFAULT_CONTEXTUAL_STRATEGY_PROMPT,
    DEFAULT_DECOMPOSITION_GENERATE_PROMPT,
    DEFAULT_DECOMPOSITION_QA_TEMPLATE,
    DEFAULT_DECOMPOSITION_SYNTHESIS_TEMPLATE,
    DEFAULT_FACTUAL_STRATEGY_PROMPT,
    DEFAULT_HYDE_FINAL_PROMPT,
    DEFAULT_HYDE_GENERATION_PROMPT,
    DEFAULT_MULTI_QUERY_PERSPECTIVES_PROMPT,
    DEFAULT_QUERY_TRANSFORMER_QUICK_MODE_INSTRUCTION,
    DEFAULT_QUERY_TRANSORMER_PROMPT,
    DEFAULT_STEP_BACK_GENERATE_PROMPT,
    DEFAULT_STEP_BACK_RESPONSE_PROMPT,
)
from src.config.prompt.quick_agent import DEFAULT_QUICK_AGENT_SYSTEM_PROMPT
from src.config.prompt.research import (
    DEFAULT_CLARIFY_WITH_USER_INSTRUCTIONS,
    DEFAULT_COMPRESS_RESEARCH_SIMPLE_HUMAN_MESSAGE,
    DEFAULT_COMPRESS_RESEARCH_SYSTEM_PROMPT,
    DEFAULT_FINAL_REPORT_GENERATION_PROMPT,
    DEFAULT_RESEARCH_SYSTEM_PROMPT,
    DEFAULT_SUMMARIZE_WEBPAGE_PROMPT,
    DEFAULT_TRANSFORM_MESSAGES_INTO_RESEARCH_TOPIC_PROMPT,
)
from src.config.prompt.retrieval import DEFAULT_RETRIEVAL_PLANNING_PROMPT, FINAL_PROMPT, GENERAL_PROMPT
from src.config.prompt.supervisor import DEFAULT_SUPERVISOR_PROMPT
from src.config.prompt.validation import DEFAULT_VALIDATION_PROMPT

# Export all prompts
__all__ = [
    # Base prompts
    "BASE_PROMPT",
    # Retrieval prompts
    "FINAL_PROMPT",
    "GENERAL_PROMPT",
    "DEFAULT_RETRIEVAL_PLANNING_PROMPT",
    # Validation prompts
    "DEFAULT_VALIDATION_PROMPT",
    # Query transformation prompts
    "DEFAULT_QUERY_TRANSORMER_PROMPT",
    "DEFAULT_QUERY_TRANSFORMER_QUICK_MODE_INSTRUCTION",
    "DEFAULT_CONTEXTUAL_STRATEGY_PROMPT",
    "DEFAULT_DECOMPOSITION_GENERATE_PROMPT",
    "DEFAULT_DECOMPOSITION_QA_TEMPLATE",
    "DEFAULT_DECOMPOSITION_SYNTHESIS_TEMPLATE",
    "DEFAULT_FACTUAL_STRATEGY_PROMPT",
    "DEFAULT_HYDE_GENERATION_PROMPT",
    "DEFAULT_HYDE_FINAL_PROMPT",
    "DEFAULT_MULTI_QUERY_PERSPECTIVES_PROMPT",
    "DEFAULT_STEP_BACK_GENERATE_PROMPT",
    "DEFAULT_STEP_BACK_RESPONSE_PROMPT",
    # Graph prompts
    "DEFAULT_GRAPH_QA_PROMPT",
    "DEFAULT_CYPHER_GENERATION_TEMPLATE",
    # Research prompts
    "DEFAULT_CLARIFY_WITH_USER_INSTRUCTIONS",
    "DEFAULT_TRANSFORM_MESSAGES_INTO_RESEARCH_TOPIC_PROMPT",
    "DEFAULT_SUPERVISOR_PROMPT",
    "DEFAULT_RESEARCH_SYSTEM_PROMPT",
    "DEFAULT_COMPRESS_RESEARCH_SYSTEM_PROMPT",
    "DEFAULT_COMPRESS_RESEARCH_SIMPLE_HUMAN_MESSAGE",
    "DEFAULT_FINAL_REPORT_GENERATION_PROMPT",
    "DEFAULT_SUMMARIZE_WEBPAGE_PROMPT",
    # Quick Agent prompts
    "DEFAULT_QUICK_AGENT_SYSTEM_PROMPT",
]
