from langgraph.graph import END, START, StateGraph

from backend.src.core.agents.query_understanding.write_research_brief import write_research_brief
from src.config.node_names import MEMORY_SUMMARIZER_NODE, RESEARCH_CLARIFY_WITH_USER, RESEARCH_FINAL_REPORT_GENERATION, RESEARCH_SUPERVISOR, RESEARCH_WRITE_RESEARCH_BRIEF
from src.config.settings import Configuration
from src.core.agents.memory.summarizer import summarizer
from src.core.agents.query_understanding.clarification import clarify_with_user
from src.core.agents.research.final_report_generation import final_report_generation
from src.core.agents.supervisor.supervisor import supervisor_subgraph
from src.schemas.state import AgentInputState, AgentState

deep_researcher_builder = StateGraph(AgentState, input=AgentInputState, config_schema=Configuration)
deep_researcher_builder.add_node(RESEARCH_CLARIFY_WITH_USER, clarify_with_user)
deep_researcher_builder.add_node(RESEARCH_WRITE_RESEARCH_BRIEF, write_research_brief)
deep_researcher_builder.add_node(RESEARCH_SUPERVISOR, supervisor_subgraph)
deep_researcher_builder.add_node(RESEARCH_FINAL_REPORT_GENERATION, final_report_generation)
deep_researcher_builder.add_node(MEMORY_SUMMARIZER_NODE, summarizer)

deep_researcher_builder.add_edge(START, MEMORY_SUMMARIZER_NODE)
deep_researcher_builder.add_edge(MEMORY_SUMMARIZER_NODE, RESEARCH_CLARIFY_WITH_USER)
deep_researcher_builder.add_edge(RESEARCH_SUPERVISOR, RESEARCH_FINAL_REPORT_GENERATION)
deep_researcher_builder.add_edge(RESEARCH_FINAL_REPORT_GENERATION, END)

deep_researcher = deep_researcher_builder.compile()
