name: Frontend CI

on:
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

jobs:
  lint-format-build:
    name: Lint, Format, and Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run Prettier (check formatting)
        run: npm run format -- --check

      - name: Run ESLint (lint)
        run: npm run lint

      - name: Build
        run: npm run build
# Best practices:
# - Use matrix to test multiple Node versions
# - Use npm cache for faster installs
# - Fail fast on lint/format errors
# - Add more jobs for test, deploy, or integration as needed
